apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracee-polr-adapter.fullname" . }}-config
  labels:
    {{- include "tracee-polr-adapter.labels" . | nindent 4 }}
data:
  config.yaml: >-
    results:
      maxPerReport: {{ .Values.results.maxPerReport }}
      minimumSeverity: {{ .Values.results.minimumSeverity }}
    rules:
      exclude:
        {{- toYaml .Values.rules.exclude | nindent 6 }}